-- ClothMorphRuntime / BodyRegistry.lua
-- Generated by tools/generate_body_registry.ps1 from tools/body_registry_manifest.json.
-- Do not hand-edit coverage here; edit the manifest and regenerate.

local M = {}

M.PROFILES = {
    bcb = { label = "BCB" },
    sbbf = { label = "SBBF" },
    vanilla = { label = "Vanilla" },
}

M.COVERAGE = {
    bcb = 3,
    sbbf = 3,
    vanilla = 0,
}

M.MAP = {
    ["bcb__0eb594cb-8820-4be6-a58d-8be7a1a98fba_10"] = "fe01f8f7-814e-5c2e-9829-a0467fd5a6ce",
    ["bcb__6c038dcb-7eb5-431d-84f8-cecfaf1c0c5a_10"] = "fe01f8f7-814e-5c2e-9829-a0467fd5a6ce",
    ["bcb__45f4ac10-3c89-4fb2-b37d-f973bb9110c0_10"] = "fe01f8f7-814e-5c2e-9829-a0467fd5a6ce",
    ["sbbf__0eb594cb-8820-4be6-a58d-8be7a1a98fba_10"] = "a22009cd-b9e9-55b1-8295-f89a0ede1bf6",
    ["sbbf__6c038dcb-7eb5-431d-84f8-cecfaf1c0c5a_10"] = "a22009cd-b9e9-55b1-8295-f89a0ede1bf6",
    ["sbbf__45f4ac10-3c89-4fb2-b37d-f973bb9110c0_10"] = "a22009cd-b9e9-55b1-8295-f89a0ede1bf6",
}

function M.BodyKey(race, bodyType, bodyShape)
    return tostring(race or "?"):lower() .. "_" .. tostring(bodyType or "?") .. tostring(bodyShape or "?")
end

function M.IsValidProfile(profile)
    return profile ~= nil and M.PROFILES[tostring(profile):lower()] ~= nil
end

function M.MapKey(profile, race, bodyType, bodyShape)
    return tostring(profile):lower() .. "__" .. M.BodyKey(race, bodyType, bodyShape)
end

function M.ResolveCcsv(profile, race, bodyType, bodyShape)
    if profile == nil or tostring(profile):lower() == "vanilla" then return nil, "vanilla" end
    local key = M.MapKey(profile, race, bodyType, bodyShape)
    return M.MAP[key], key
end

return M
